language: node_js
dist: trusty
node_js: stable
sudo: required

env:
  - NODE_ENV=production
  - BABEL_ENV=production
install:
  - npm install -g truffle
  - npm install
  - truffle compile
  # add truffle deploy
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_webpack/
  on:
  branch: master
