language: node_js
dist: trusty
node_js: stable
sudo: required

env:
  - NODE_ENV=production BABEL_ENV=production
install:
  - yarn global add truffle
  - yarn install
script:
  - truffle compile
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_webpack/
  on:
  branch: master
